### ISSUE TITLE
[5/20 9:00] 別のFPライブラリを試す

### ISSUE THREAD

**Issue by exKAZUu** [tokichie/Minyar#10]
期日までにプルリクを作って， @ina-yuzen か @exKAZUu がたしかにやったと判定したらOK．

**Comment by tokichie** [comment]
https://github.com/SohaibAjmal/DataMining-Project-CSharp
を使おうと思ったのですが、ソースコードを読んだ感じだと前のライブラリのほうが汎用性が高く、ライブラリの返り値もFrequentなstringを返してくれるだけでちょっと使えなさそうでした。。
